---
- name: Install secrets for ArgoCD
  hosts: masters
  become: true
  vars_files:
    - vars/github.yml
    - vars/k8s.yml
  roles:
    - argocd-secrets

- name: Install secrets prior to deploying GoFlights application
  hosts: masters
  become: true
  vars_files:
    - vars/k8s.yml
  roles:
    - app-secrets

- name: Install secrets prior to deploying Monitoring application
  hosts: masters
  become: true
  vars_files:
    - vars/k8s.yml
  roles:
    - monitoring-secrets
