---
# Note: Error saying externally managed package
# Belo commented lines dont work

# - name: Install pip for Python 3
#   ansible.builtin.package:
#     name: python3-pip
#     state: present

# - name: Install kubernetes python package
#   ansible.builtin.pip:
#     name: kubernetes

- name: Install kubernetes python package
  ansible.builtin.package:
    name: python3-kubernetes
    state: present
