---
# This follows the official documentation provided by Kubernetes to install using kubeadm
# https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/
- name: Install prerequisites for kubernetes
  ansible.builtin.package:
    name:
    - ca-certificates
    - curl
    - gnupg
    state: present
    update_cache: true

# Specific to Ubuntu
- name: Ensure /etc/apt/keyrings directory exists
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: "0755"

# Specific to Ubuntu
- name: Add Kubernetes GPG key
  ansible.builtin.get_url:
    url: "https://pkgs.k8s.io/core:/stable:/v1.34/deb/Release.key"
    dest: /etc/apt/keyrings/kubernetes.asc
    mode: "0644"

# Specific to Ubuntu
- name: Convert Kubernetes GPG key to ASCII armored format
  ansible.builtin.command: >
    gpg --batch --true --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg /etc/apt/keyrings/kubernetes.asc

# Specific to Ubuntu
- name: Add Kubernetes repository
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.34/deb/ /"
    state: present

# Master nodes

- name: Install Kubernetes components (control plane)
  ansible.builtin.package:
    name:
    - kubelet
    - kubeadm
    - kubectl
    state: present
    update_cache: true
  when: "'masters' in group_names"

# Specific to Ubuntu
- name: Mark Kubernetes packages to hold (control plane)
  ansible.builtin.apt:
    name:
    - kubelet
    - kubeadm
    - kubectl
    allow_change_held_packages: false
  when: "'masters' in group_names"

# Worker nodes

- name: Install Kubernetes components (worker nodes)
  ansible.builtin.package:
    name:
    - kubelet
    - kubeadm
    state: present
    update_cache: true
  when: "'workers' in group_names"

# Specific to Ubuntu
- name: Mark Kubernetes packages to hold (worker nodes)
  ansible.builtin.apt:
    name:
    - kubelet
    - kubeadm
    allow_change_held_packages: false
  when: "'workers' in group_names"

# Start kubelet on all nodes
- name: Enable and start kubelet service
  ansible.builtin.systemd:
    name: kubelet
    state: restarted
    daemon_reload: true
    enabled: true
  register: kubelet_status
