---
- name: Create terraform.tfvars.json from template
  template:
    src: tfvars.json.j2
    dest: ../terraform-vmware-esxi-multiple-vm/terraform.tfvars.json

- name: Run terraform init
  command: terraform init
  args:
    chdir: ../terraform-vmware-esxi-multiple-vm/

- name: Run terraform apply
  command: terraform apply -auto-approve
  args:
    chdir: ../terraform-vmware-esxi-multiple-vm/

- name: Get Terraform output (Ansible inventory)
  command: terraform output -raw ansible_inventory
  register: tf_inventory
  args:
    chdir: ../terraform-vmware-esxi-multiple-vm/

- name: Write Ansible inventory to file
  copy:
    content: "{{ tf_inventory.stdout }}"
    dest: ./ansible_vms_inventory.ini

